import re
phRegex = re.compile(r'\(\d\d\d\) \d\d\d-\d\d\d\d')
#print(phRegex)
website = '''
CodeBeautify Logo
Random Phone Number
 
10
 Add Parenthesis
(206) 342-8631
Seattle, WA

(717) 550-1675
Harrisburg, PA

(248) 762-0356
Farmington Hills, MI

(253) 644-2182
Auburn, WA

(212) 658-3916
New York City, NY

(209) 300-2557
Ceres, CA

(262) 162-1585
Menomonee Falls, WI

(252) 258-3799
Greenville, NC

(234) 109-6666
Akron, OH

(201) 874-8593
Bayonne, NJ

Showing 10 Numbers
Random Phone Number Online
Random Phone Number tool helps to generate fake phone numbers. But these phone numbers are completely random and generated by browser or device in US phone number format.

A phone number is a string of digits assigned to a specific telephone line. Phone numbers are one of the most common things we see daily. They're on every street corner, every advertisement we see, and all our email accounts.

Advantages of Random Phone Number Generator:
Data Testing and Validation: It's often used in software development and database testing to develop model data or test methods.
Privacy Protection: Some users may like to maintain their phone numbers private when filling out forms or signing up for assistance online due to privacy circumstances.
Online Advertising and Marketing: Marketers and advertisers sometimes use this tool to create a pool of phone numbers for promotional campaigns or giveaways.
Educational Purposes: It can be used in educational settings to teach students about number patterns, probability, or data analysis.
Prank Calls or Entertainment: While not encouraged, some people may use it for prank calls or as a source of entertainment.
Any generated phone numbers should not be used for illegal or harmful activities.

Phone numbers are used for telecommunication purposes and may be used in the public switched telephone network or other telecommunications networks to route telephone calls.

Know more about Phone Number on Wikipedia

What can you do with Random Phone Number Tool?
It helps to generate phone numbers and you can share them with your friends. Mostly all phone numbers are fake but the area code is not fake it's real.
This tool can be used for fun and know about different phone numbers.
Online Random Phone Number tool works well on Windows, MAC, Linux, Chrome, Firefox, Edge, and Safari.
Code Beautify
Color Converters

HEX to Pantone Converter
RGB to Pantone Converter
HSV to Pantone Converter
CMYK to Pantone Converter
CMYK to HEX Converter
CMYK to RGB Converter
CMYK to HSV Converter
HSV to HEX Converter
HSV to RGB Converter
HSV to CMYK Converter
HEX to HSV Converter
RGB to HEX Converter
RGB to HSV Converter
RGB to CMYK Converter
HEX to RGB Converter
HEX to CMYK Converter
Pantone to HEX Converter
Pantone to RGB Converter
Pantone to CMYK Converter
Pantone to HSV Converter
Unit Converter

Length Converter
Weight Converter
Volume Converter
Area Converter
Time Converter
Unix Timestamp Converter
More Unit Tools
SQL Converters

SQL to CSV Converter
SQL to JSON Converter
SQL to XML Converter
SQL to YAML Converter
SQL to HTML Converter
Encode and Decode

Base32 Encode
Base32 Decode
Base58 Encode
Base58 Decode
Base64 Encode
Base64 Decode
URL Encode Online
URL Decode Online
JSON URL Encode
JSON URL Decode
HTML Encode
HTML Decode
XML URL Encoding
XML URL Decoding
UTF8 Converter
UTF8 Decode
Hex to UTF8
JSON Decode Online
JSON Encode Online
Base64 Tools

Image to Base64
Base64 to Image
PNG to Base64
JPG to Base64
JSON to Base64
XML to Base64
YAML to Base64
Base64 to JSON
Base64 to XML
Base64 to YAML
CSV to Base64
Base64 to CSV
TSV to Base64
Base64 to TSV
Binary to Base64
Base64 to Binary
Hex to Base64
Base64 to Hex
Octal to Base64
More Base64 Tools
Image Tools

JPG to PNG
BMP to PNG
PNG to JPG
GIF Splitter
GIF Viewer
More Image Tools
Converters

Image to Base64
Base64 to Image
Date Calculater
EXCEL to HTML
EXCEL to XML
EXCEL to JSON
OPML to JSON
Word to HTML
Online Tableizer
JSON Converters

JSON to JAVA
JSON to XML
JSON to YAML
JSON to CSV
JSON to TSV
JSON to Text
JSON to Excel
JSON to HTML
XML Converters

XML Converter
XML to JSON
XML to YAML
XML to CSV
XML to TSV
XML to Text
XML-XSL Transform
XML to HTML
XML to Excel
XML to JAVA
HTML Converters

HTML Stripper
HTML Table Generator
HTML to CSV Converter
HTML to TSV Converter
HTML to PHP Converter
HTML to CSV
HTML to JSON
HTML to XML
HTML to YAML
HTML to Text
Text to HTML Entities
HTML Entities to Text
HTML to Markdown
Markdown to HTML
PUG to HTML Converter
HTML to PUG Converter
JADE to HTML Converter
HTML to JADE Converter
HTML to BBCode Converter
BBCode to HTML Converter
YAML Converters

YAML Converter
YAML to XML
YAML to JSON
YAML to CSV
YAML to Excel
Utility

Send Snap Message
Responsive Website Tester
Credit Card Validator
Credit Card Fake Number Generator
XPath Tester
JSON Path Tester
JSON Minifier
File Difference
JSON Diff
XML Diff
Broken Link Checker
JSON Deserialize Online
JSON Serialize Online
JSON Stringify Online
XML Stringify Online
String to JSON Online
JavaScript Obfuscator
Curl to PHP
Crontab Format
Chart Tools

Line Graph Maker
Bar Graph Maker
Pie Chart Maker
Doughnut Chart Maker
Scatter Plot Maker
Viewers

JSON Viewer
XML Viewer
YAML Viewer
MXML Viewer
HTML Viewer
JavaScript Viewer
RSS Viewer
SOURCE CODE Viewer
OPML Viewer
CSV Viewer
BBCode Viewer
Markdown Viewer
Programming Editors

XML Editor
JSON Editor
Real Time HTML Editor
YAML Editor
ONLINE Editor
JAVA Editor
C# Editor
Actionscript Editor
Markdown Editor
Parsers

URL Parser
JSON Parser
XML Parser
YAML Parser
CSS Tools

CSS Beautifier
CSS to LESS
CSS to SCSS
CSS to SASS
CSS to Stylus
Stylus Compiler
Stylus to CSS
Stylus to LESS
Stylus to SCSS
Stylus to SASS
LESS Compiler
LESS to CSS
LESS to Stylus
LESS to SCSS
LESS to SASS
SCSS Compiler
SCSS to CSS
SCSS to Stylus
SCSS to LESS
SCSS to SASS
SASS Compiler
SASS to CSS
SASS to Stylus
SASS to SCSS
SASS to LESS
Escape Unescape

HTML Escape Unescape
XML Escape Unescape
Java Escape Unescape
C# Escape Unescape
Javascript Escape Unescape
CSV Escape Unescape
SQL Escape Unescape
JSON Escape Unescape
Un-Google Link
CryptoGraphy Tools

Encryption-Decryption
HMAC Generator
MD2 Hash Generator
MD4 Hash Generator
MD5 Hash Generator
MD6 Hash Generator
NTLM Hash Generator
SHA1 Hash Generator
SHA2 Hash Generator
SHA224 Hash Generator
SHA256 Hash Generator
SHA384 Hash Generator
SHA512 Hash Generator
SHA512/224 Hash Generator
SHA512/256 Hash Generator
SHA3-224 Hash Generator
SHA3-256 Hash Generator
SHA3-384 Hash Generator
SHA3-512 Hash Generator
CRC-16 Hash Generator
CRC-32 Hash Generator
Shake-128 Hash Generator
Shake-256 Hash Generator
Whirlpool Hash Generator
Wordpress Password Hash Generator
Beautifiers

JSON Beautifier
CSS Beautifier
XML Beautifier
Javascript Beautifier
YAML Beautifier
C# Beautifier
Java Beautifier
C Beautifier
C++ Beautifier
TypeScript Formatter
SQL Formatter
Babel Formatter
Markdown Formatter
MDX Formatter
LESS Beautifier
SCSS Beautifier
GraphQL Beautifier
PHP Beautifier
Python Beautifier
Perl Beautifier
Ruby Beautifier
Angular Formatter
React Formatter
Lua Beautifier
XAML Beautifier
Minifier

JSON Minify
XML Minify
Minify JS
CSS Minify
SQL Minifier
Minify HTML
Lua Minifier
Text Minifier
CSV Tools

CSV Viewer
CSV to XML/JSON
CSV to XML
CSV to JSON
CSV to HTML
CSV to TSV
CSV to MULTILINE DATA
CSV to SQL
CSV to Excel
String Utilities

Upside Down Text
Random Word Generator
NTLM Hash Generator
Password Generator
String Builder
Number to Word Converter
Word to Number Converter
WORD COUNTER
Word Repeater
Reverse String
String to Hex Converter
Hex to String Converter
String to Binary Converter
Binary to String Converter
Case Converter
Delimited Text Extractor
Remove Accents
Remove Duplicate Lines
Remove Empty Lines
Remove Extra Spaces
Remove Whitespace
Remove Line Breaks
Remove Lines Containing
Sort Text Lines
Word Sorter
Word Frequency Counter
Text Repeater
Remove Punctuation
Syntax Highlighting

JSON Syntax Highlighting
XML Highlighter
XML Pretty Print
HTML Pretty Print
JS Pretty Print
Code Highlighter
Compress / Decompress

GZip Decompress Online
Zlib Decompress Online
Validators

CSS Validator
JavaScript Validator
JSON Validator
JSON5 Validator
XML Validator
Credit Card Validator
API Test
YAML Validator
Number Utilities

All Numbers Converter
Decimal to Binary
Decimal to Octal
Binary to Decimal
Binary to Hex
Binary to Octal
Hex to Decimal
Hex to Binary
Hex to Octal
Octal toDecimal
Octal to Binary
Octal to Hex
Binary to Text
Text to Binary
ASCII to Text
Char to ASCII
Reverse Hex
Bitwise Tools

Bitwise Calculator
XOR Calculator
AND Calculator
NAND Calculator
OR Calculator
NOR Calculator
XNOR Calculator
IP Tools

Hex to IP
IP to Hex
Binary to IP
IP to Binary
Decimal to IP
IP to Decimal
Octal to IP
IP to Octal
IPV6 to Binary
Other Tools

Lorem-Ipsum
Sharelink Generator
Hostname to IP
IP to Hostname
Phone to IP Address
IP Address to Phone
DNS Lookup
MX Lookup
Nameserver Lookup
Website to IP Address
Open Port Checker
Webcam Test
Random Tools

Random IP Address
Random Time Generator
Random UUID Generator
Random JSON Generator
Random XML Generator
Random Data from Regex
Random CSV Generator
Random Number Generator
Random Integer Generator
Random Prime Generator
Random Date Generator
Random Bitmap Generator
Random Name Picker
Text Lines shuffler
MAC Address Generator
Random Hex Generator
Random TSV Generator
Random String Generator
Random Fraction Generator
Random Integer Range Generator
Random Binary Generator
Random Byte Generator
Random Decimal Generator
Random Alphanumeric Generator
Copyright © CodeBeautify 2023 | v8.7


Built with  and  for you...

'''

print(phRegex.findall(website),'\n')
phRegex = re.compile(r'(\(\d\d\d\)) (\d\d\d-\d\d\d\d)')#2 groups
print(phRegex.findall(website),'\n')
phRegex = re.compile(r'((\(\d\d\d\)) (\d\d\d-\d\d\d\d))')#3 groups
print(phRegex.findall(website),'\n')
phRegex = re.compile(r'(\(\d\d\d\)) \d\d\d-\d\d\d\d')#1 group
print(phRegex.findall(website),'\n')
#the findall either returns a list of strings or a list of tuples with strings

#the fucking pain
phRegex = re.compile(r'\
(\(\d\d\d\) \d\d\d-\d\d\d\d\
|\d\d\d\-\d\d\d-\d\d\d\d\
|\d\d\d\ \d\d\d \d\d\d\d\
|\(\d\d\d\)-\d\d\d-\d\d\d\d)')
print(phRegex.findall(website))
'''this caused so much pain so I'm gonna talk about it. THE ANSWER WAS
PIPELINES. I tried to figure out how to give it multiple options based on
how the text was formatted so I could detect it regardless, but it always
just returned a jumble of spaces probably because of the groups I added.
But by adding pipelines in between each option, it doesn't give me those
jumbles anymore.
However...it turns out that there might be an even simpler solution, in
the form of character classes and
utilizing +,*, and ? without using parathesis.

'''
phRegex = re.compile(r'\
(\(\d+\) \d+-\d+\
|\d+-\d+-\d+\
|\d+\s\d+\s\d+\
|\(\d+\)-\d+-\d+)')
print(phRegex.findall(website))
#Character Classes
#examples of a character class is \d representing any digit for a pattern
'''
    \d - Any numeric digit from 0 to 9
    \D - Any character that is not a numeric digit from 0 to 9
    \w - Any letter, numeric digit, or underscore character. Doesn't
include any punctuation
    \W - Any character that is not a letter, numeric digit or the
underscore character
    \s - Any space, tab, or newline character
    \S - Any character that is not a space, tab, or newline
'''

lyrics = """
On the twelfth day of Christmas
my true love sent to me:
12 Drummers Drumming
11 Pipers Piping
10 Lords a Leaping
9 Ladies Dancing
8 Maids a Milking
7 Swans a Swimming
6 Geese a Laying
5 Golden Rings
4 Calling Birds
3 French Hens
2 Turtle Doves
and 1 Partridge in a Pear Tree
"""
cmasRegex = re.compile(r'\d+\s\w+')
xmasRegex = re.compile(r'\d+\s\w+\s\w+\s\w+')
print(cmasRegex.findall(lyrics))
print(xmasRegex.findall(lyrics))


#Make your own character classes
vowelRegex = re.compile(r'[aeiouAEIOU]') #same as r'(a|e|i|o|u)' but better
#alphRegex = re.compile(r'[a-z]')#python understands this as any lowercase
#letter from a to z.alphRegex = re.compile(r'[a-zA-Z]')for capital letters too
print(vowelRegex.findall('Robocop eats baby instead of baby food'))
doubleVowelRegex = re.compile(r'[aeiouAEIOU]{2}')
print(doubleVowelRegex.findall('Robocop eats baby instead of baby food'))

consonantRegex = re.compile(r'[^aeiouAEIOU]')
print(consonantRegex.findall('Robocop eats baby instead of baby food'))
#the to the power symbol means to find everything not specified in the regex
#calling it consonantRegex isn't accurate since it finds commas and spaces



